# -*- coding: utf-8 -*-
"""3_indiv_task_prices.txt.ipynb

Automatically generated by Colab.
"""

filename = '/content/prices.txt'

with open(filename, 'r') as file:
  prices = file.read()

total_price = 0.0
total_items = 0

lines = prices.splitlines()

for line in lines:
    line = line.strip()
    try:
        price = float(line)
        total_price += price
        total_items += 1
    except ValueError:
        continue

print(prices)
print()
print(f"Total Price: {total_price:.2f} EUR")
print(f"Total Number of Items: {total_items}")
